import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { getCoachProfile } from '@/components/utils/coachProfiles'
import { checkRateLimit, getClientIdentifier, RATE_LIMITS } from '@/lib/rateLimit'
import { supabase } from '@/lib/supabase'
import { logger, generateRequestId } from '@/lib/logger'
import { requireCsrfToken, shouldEnforceCsrf } from '@/lib/csrf'
import type { ChatResponse, ChatErrorResponse } from '@/types/api'

export const runtime = 'edge'

// Request validation schema
const ChatRequestSchema = z.object({
  messages: z.array(z.object({
    role: z.enum(['user', 'assistant', 'system']),
    content: z.string().min(1).max(10000)
  })).min(1).max(50),
  // userData is a pre-formatted context string generated by generateUserContext()
  // Contains workout history, body stats, nutrition data, and user profile
  userData: z.string().max(50000).optional(),
  coachProfile: z.enum(['motiverend', 'streng', 'wetenschappelijk', 'vriendelijk', 'powerlifting', 'bodybuilding']).optional()
})

export async function POST(request: NextRequest) {
  const startTime = Date.now()
  const requestId = generateRequestId()
  let userId: string | undefined
  
  try {
    // CSRF Protection (only in production by default)
    if (shouldEnforceCsrf()) {
      const csrfError = requireCsrfToken(request)
      if (csrfError) {
        logger.warn('CSRF token validation failed', { requestId, endpoint: '/api/chat' })
        return csrfError
      }
    }

    // Get authorization header
    const authHeader = request.headers.get('authorization')
    if (!authHeader?.startsWith('Bearer ')) {
      logger.authLog('auth_failure', undefined, { requestId, endpoint: '/api/chat' })
      return NextResponse.json(
        { error: 'Unauthorized - No valid session' },
        { status: 401 }
      )
    }

    const token = authHeader.substring(7)
    
    // Verify session with Supabase
    const { data: { user }, error: authError } = await supabase.auth.getUser(token)
    
    if (authError || !user) {
      logger.authLog('auth_failure', undefined, { requestId, endpoint: '/api/chat', error: authError?.message })
      return NextResponse.json(
        { error: 'Unauthorized - Invalid session' },
        { status: 401 }
      )
    }

    userId = user.id

    // Rate limiting
    const identifier = getClientIdentifier(request, user.id)
    const rateLimit = checkRateLimit(identifier, RATE_LIMITS.AI_CHAT)
    
    if (!rateLimit.success) {
      logger.rateLimitLog(user.id, '/api/chat', RATE_LIMITS.AI_CHAT.limit)
      return NextResponse.json(
        { 
          error: 'Rate limit exceeded. Please try again later.',
          retryAfter: Math.ceil((rateLimit.reset - Date.now()) / 1000)
        },
        { 
          status: 429,
          headers: {
            'X-RateLimit-Limit': rateLimit.limit.toString(),
            'X-RateLimit-Remaining': rateLimit.remaining.toString(),
            'X-RateLimit-Reset': rateLimit.reset.toString(),
            'Retry-After': Math.ceil((rateLimit.reset - Date.now()) / 1000).toString()
          }
        }
      )
    }

    // Parse and validate request body
    const body = await request.json()
    const validation = ChatRequestSchema.safeParse(body)
    
    if (!validation.success) {
      logger.warn('Chat request validation failed', { 
        requestId, 
        userId,
        errors: validation.error.format() 
      });
      
      return NextResponse.json(
        { 
          error: 'Invalid request: Please check your message format',
          details: process.env.NODE_ENV === 'development' ? validation.error.format() : undefined
        } satisfies ChatErrorResponse,
        { status: 400 }
      )
    }

    const { messages, userData, coachProfile } = validation.data
    
    // Additional validation
    if (!messages || messages.length === 0) {
      return NextResponse.json(
        { error: 'At least one message is required' } satisfies ChatErrorResponse,
        { status: 400 }
      )
    }

    // Get the coach profile configuration
    const profile = getCoachProfile(coachProfile || 'motiverend')
    
    const systemPrompt = `${profile.systemPrompt}

Je hebt toegang tot uitgebreide gebruikersdata inclusief:
- 1RM progressies en trends per oefening
- Strength Score (som van grote lifts)
- Recente PRs (Personal Records)
- Plateau detectie (oefeningen zonder progressie)
- Volume statistieken per workout en per week
- Lichaamsmetingen en trends
- Voedingsinname vs. doelen (TDEE, macro's)
- Gebruikersprofiel (leeftijd, gewicht, lengte, activiteitsniveau)

Gebruik deze data om:
- Specifieke, data-gedreven adviezen te geven
- Plateaus te identificeren en oplossingen aan te dragen
- Workout schema's te genereren gebaseerd op frequentie en progressie
- Voedingsschema's voor te stellen op basis van TDEE en macro-doelen
- Trends te analyseren en te voorspellen
- Motivatie te geven op basis van recente achievements

Antwoord ALTIJD in het Nederlands. Wees beknopt maar informatief (max 3-4 alinea's).
Als je een workout of maaltijdplan maakt, gebruik dan een duidelijke structuur.

GEBRUIKERSDATA:
${userData}`

    const llmResponse = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
        'HTTP-Referer': process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
        'X-Title': 'NEXT-REP Fitness Tracker',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'x-ai/grok-4.1-fast',
        messages: [
          { role: 'system', content: systemPrompt },
          ...messages
        ],
        temperature: 0.7,
        max_tokens: 800,
      }),
    })

    if (!llmResponse.ok) {
      const errorText = await llmResponse.text();
      logger.error('OpenRouter API error', new Error(errorText), {
        requestId,
        userId,
        statusCode: llmResponse.status,
        endpoint: '/api/chat'
      });
      
      return NextResponse.json(
        { 
          error: 'AI service temporarily unavailable. Please try again.',
          retryAfter: llmResponse.status === 429 ? 60 : undefined
        } satisfies ChatErrorResponse,
        { status: llmResponse.status >= 500 ? 503 : llmResponse.status }
      )
    }

    const data = await llmResponse.json();
    
    // Validate response structure
    if (!data.choices?.[0]?.message?.content) {
      logger.error('Invalid OpenRouter response structure', new Error('Missing content'), {
        requestId,
        userId,
        responseData: data
      });
      
      return NextResponse.json(
        { error: 'Received invalid response from AI service' } satisfies ChatErrorResponse,
        { status: 502 }
      )
    }
    
    const aiMessage = data.choices[0].message.content;

    // Log successful API request
    logger.apiLog({
      requestId,
      userId,
      endpoint: '/api/chat',
      method: 'POST',
      statusCode: 200,
      duration: Date.now() - startTime
    })

    const response: ChatResponse = {
      message: aiMessage,
      model: 'anthropic/claude-3.5-sonnet'
    };

    return NextResponse.json(
      response,
      {
        headers: {
          'X-RateLimit-Limit': rateLimit.limit.toString(),
          'X-RateLimit-Remaining': rateLimit.remaining.toString(),
          'X-RateLimit-Reset': rateLimit.reset.toString()
        }
      }
    )

  } catch (error) {
    const isClientError = error instanceof SyntaxError; // JSON parse error
    const statusCode = isClientError ? 400 : 500;
    
    logger.error('Error in AI chat', error, {
      requestId,
      userId,
      endpoint: '/api/chat',
      isClientError
    })
    
    return NextResponse.json(
      { 
        error: isClientError 
          ? 'Invalid request format' 
          : 'An unexpected error occurred. Please try again.'
      } satisfies ChatErrorResponse,
      { status: statusCode }
    )
  }
}
