/**
 * Nutrition Search Types
 * Interfaces for Open Food Facts, USDA FoodData Central, and unified search results
 */

// ===== Open Food Facts Types =====
export interface OpenFoodFactsNutrients {
  'energy-kcal_100g'?: number;
  'proteins_100g'?: number;
  'carbohydrates_100g'?: number;
  'fat_100g'?: number;
  'fiber_100g'?: number;
  'sugars_100g'?: number;
  'salt_100g'?: number;
  'sodium_100g'?: number;
}

export interface OpenFoodFactsProduct {
  product_name?: string;
  product_name_nl?: string;
  brands?: string;
  nutriments?: OpenFoodFactsNutrients;
  serving_size?: string;
  quantity?: string;
  image_url?: string;
  code?: string; // barcode
}

export interface OpenFoodFactsResponse {
  count: number;
  page: number;
  page_size: number;
  products: OpenFoodFactsProduct[];
}

// ===== USDA FoodData Central Types =====
export interface USDANutrient {
  nutrientId: number;
  nutrientName: string;
  nutrientNumber: string;
  unitName: string;
  value: number;
}

export interface USDAFood {
  fdcId: number;
  description: string;
  dataType: string;
  brandOwner?: string;
  foodNutrients: USDANutrient[];
  servingSize?: number;
  servingSizeUnit?: string;
}

export interface USDAResponse {
  totalHits: number;
  currentPage: number;
  totalPages: number;
  foods: USDAFood[];
}

// ===== Unified Search Result =====
export interface NutritionSearchResult {
  id: string; // Unique identifier (OFF code or USDA fdcId)
  name: string; // Product name
  brand?: string; // Brand name if available
  source: 'openfoodfacts' | 'usda'; // Data source
  
  // Nutrients per 100g/100ml (standardized)
  nutrients: {
    calories: number; // kcal
    protein: number; // g
    carbs: number; // g
    fats: number; // g
    fiber?: number; // g (optional)
    sugars?: number; // g (optional)
    sodium?: number; // mg (optional)
  };
  
  // Metadata
  servingSize?: string; // e.g., "100ml", "1 slice (30g)"
  imageUrl?: string;
}

// ===== API Request/Response Types =====
export interface NutritionSearchRequest {
  query: string; // Search term (Dutch)
  limit?: number; // Max results (default: 10)
}

export interface NutritionSearchResponse {
  results: NutritionSearchResult[];
  totalResults: number;
  cached: boolean; // Whether results came from cache
  sources: {
    openfoodfacts: number; // Number of results from OFF
    usda: number; // Number of results from USDA
  };
  pagination?: {
    currentPage: number;
    pageSize: number;
    hasMore: boolean;
  };
}

// ===== Cache Entry =====
export interface CachedSearchEntry {
  query: string;
  results: NutritionSearchResult[];
  timestamp: number; // Unix timestamp
  ttl: number; // Time to live in ms (default: 24 hours)
}

// ===== Meal Templates (Presets) =====
export type MealCategory = 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'other';

export interface MealTemplateItem {
  id: string;
  templateId: string;
  
  // Food details
  foodName: string;
  foodBrand?: string;
  
  // Nutritional info per 100g (baseline)
  caloriesPer100g: number;
  proteinPer100g: number;
  carbsPer100g: number;
  fatsPer100g: number;
  
  // Quantity in template
  quantity: number; // e.g., 200 for 200g
  unit: string; // 'g', 'ml', 'piece', 'scoop', etc.
  
  // Optional reference
  foodItemId?: string; // Barcode or OFF/USDA ID
  customNotes?: string;
  
  createdAt?: string;
}

export interface MealTemplate {
  id: string;
  userId: string;
  name: string;
  category?: MealCategory;
  isAutoGenerated?: boolean; // True if suggested by algorithm
  usageCount: number; // Track popularity
  items: MealTemplateItem[]; // Joined items
  createdAt?: string;
  updatedAt?: string;
  
  // Computed fields (not in DB)
  totalCalories?: number;
  totalProtein?: number;
  totalCarbs?: number;
  totalFats?: number;
}

// ===== API Request/Response for Templates =====
export interface CreateTemplateRequest {
  name: string;
  category?: MealCategory;
  items: Omit<MealTemplateItem, 'id' | 'templateId' | 'createdAt'>[];
}

export interface UpdateTemplateRequest {
  name?: string;
  category?: MealCategory;
  items?: Omit<MealTemplateItem, 'id' | 'templateId' | 'createdAt'>[];
}

export interface LogTemplateRequest {
  templateId: string;
  date: string; // ISO date YYYY-MM-DD
  adjustments?: { // Optional per-item quantity adjustments
    itemId: string;
    quantity: number;
  }[];
}

export interface TemplateSuggestion {
  template: Omit<MealTemplate, 'id' | 'userId'>; // Suggested template (not yet saved)
  confidence: number; // 0-1 score based on frequency
  occurrences: number; // How many times this combo appeared
  lastSeen: string; // ISO timestamp
}

// ===== CUSTOM FOOD ITEMS =====
// User-defined food items with manual nutritional values

export interface CustomFoodItem {
  id: string;
  userId: string;
  name: string;
  brand?: string; // Optional brand/restaurant name
  
  // Nutritional values (per serving size)
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  
  // Serving info
  servingSize: number; // e.g., 300 for a 300g meal
  servingUnit: string; // 'g', 'ml', 'piece', 'portion', etc.
  
  // Additional info
  category?: string; // 'meal', 'snack', 'drink', 'dessert', etc.
  notes?: string;
  
  // Usage tracking
  usageCount: number;
  lastUsedAt?: string; // ISO timestamp
  
  createdAt?: string;
  updatedAt?: string;
}

// ===== API Request/Response for Custom Food Items =====
export interface CreateCustomFoodItemRequest {
  name: string;
  brand?: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  servingSize: number;
  servingUnit: string;
  category?: string;
  notes?: string;
}

export interface UpdateCustomFoodItemRequest {
  name?: string;
  brand?: string;
  calories?: number;
  protein?: number;
  carbs?: number;
  fats?: number;
  servingSize?: number;
  servingUnit?: string;
  category?: string;
  notes?: string;
}
