/**
 * Meal Templates Service
 * CRUD operations for meal templates and automatic suggestions
 */

import { supabase } from '@/lib/supabase';
import { 
  MealTemplate, 
  MealTemplateItem, 
  MealCategory,
  TemplateSuggestion,
  CreateTemplateRequest 
} from '@/types/nutrition';
import { NutritionItem, NutritionLog } from '@/components/context/DataContext';

// ===== DATABASE HELPERS =====

/**
 * Convert database row to MealTemplate with joined items
 */
function mapDbRowToTemplate(row: any): MealTemplate {
  const items: MealTemplateItem[] = row.meal_template_items?.map((item: any) => ({
    id: item.id,
    templateId: item.template_id,
    foodName: item.food_name,
    foodBrand: item.food_brand,
    caloriesPer100g: parseFloat(item.calories_per_100g),
    proteinPer100g: parseFloat(item.protein_per_100g),
    carbsPer100g: parseFloat(item.carbs_per_100g),
    fatsPer100g: parseFloat(item.fats_per_100g),
    quantity: parseFloat(item.quantity),
    unit: item.unit,
    foodItemId: item.food_item_id,
    customNotes: item.custom_notes,
    createdAt: item.created_at
  })) || [];

  // Calculate totals
  const totals = items.reduce((acc, item) => {
    const multiplier = item.quantity / 100;
    return {
      calories: acc.calories + (item.caloriesPer100g * multiplier),
      protein: acc.protein + (item.proteinPer100g * multiplier),
      carbs: acc.carbs + (item.carbsPer100g * multiplier),
      fats: acc.fats + (item.fatsPer100g * multiplier)
    };
  }, { calories: 0, protein: 0, carbs: 0, fats: 0 });

  return {
    id: row.id,
    userId: row.user_id,
    name: row.name,
    category: row.category as MealCategory,
    isAutoGenerated: row.is_auto_generated,
    usageCount: row.usage_count,
    items,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    totalCalories: Math.round(totals.calories),
    totalProtein: Math.round(totals.protein * 10) / 10,
    totalCarbs: Math.round(totals.carbs * 10) / 10,
    totalFats: Math.round(totals.fats * 10) / 10
  };
}

// ===== CRUD OPERATIONS =====

/**
 * Get all templates for a user
 */
export async function getMealTemplates(userId: string): Promise<MealTemplate[]> {
  try {
    const { data, error } = await supabase
      .from('meal_templates')
      .select(`
        *,
        meal_template_items (*)
      `)
      .eq('user_id', userId)
      .order('usage_count', { ascending: false });

    if (error) {
      console.error('Error fetching meal templates:', error);
      return [];
    }

    return (data || []).map(mapDbRowToTemplate);
  } catch (err) {
    console.error('Exception fetching meal templates:', err);
    return [];
  }
}

/**
 * Get single template by ID
 */
export async function getMealTemplate(templateId: string): Promise<MealTemplate | null> {
  try {
    const { data, error } = await supabase
      .from('meal_templates')
      .select(`
        *,
        meal_template_items (*)
      `)
      .eq('id', templateId)
      .single();

    if (error || !data) {
      console.error('Error fetching template:', error);
      return null;
    }

    return mapDbRowToTemplate(data);
  } catch (err) {
    console.error('Exception fetching template:', err);
    return null;
  }
}

/**
 * Create new meal template
 */
export async function createMealTemplate(
  userId: string,
  request: CreateTemplateRequest
): Promise<MealTemplate | null> {
  try {
    // 1. Create template
    const { data: templateData, error: templateError } = await supabase
      .from('meal_templates')
      .insert({
        user_id: userId,
        name: request.name,
        category: request.category || 'other',
        is_auto_generated: false,
        usage_count: 0
      })
      .select()
      .single();

    if (templateError || !templateData) {
      console.error('Error creating template:', templateError);
      return null;
    }

    // 2. Create template items
    const itemsToInsert = request.items.map(item => ({
      template_id: templateData.id,
      food_name: item.foodName,
      food_brand: item.foodBrand,
      calories_per_100g: item.caloriesPer100g,
      protein_per_100g: item.proteinPer100g,
      carbs_per_100g: item.carbsPer100g,
      fats_per_100g: item.fatsPer100g,
      quantity: item.quantity,
      unit: item.unit,
      food_item_id: item.foodItemId,
      custom_notes: item.customNotes
    }));

    const { error: itemsError } = await supabase
      .from('meal_template_items')
      .insert(itemsToInsert);

    if (itemsError) {
      console.error('Error creating template items:', itemsError);
      // Rollback: delete template
      await supabase.from('meal_templates').delete().eq('id', templateData.id);
      return null;
    }

    // 3. Fetch complete template with items
    return await getMealTemplate(templateData.id);
  } catch (err) {
    console.error('Exception creating meal template:', err);
    return null;
  }
}

/**
 * Update existing meal template
 */
export async function updateMealTemplate(
  templateId: string,
  updates: Partial<CreateTemplateRequest>
): Promise<MealTemplate | null> {
  try {
    // 1. Update template metadata if provided
    if (updates.name || updates.category) {
      const { error: updateError } = await supabase
        .from('meal_templates')
        .update({
          name: updates.name,
          category: updates.category
        })
        .eq('id', templateId);

      if (updateError) {
        console.error('Error updating template:', updateError);
        return null;
      }
    }

    // 2. Update items if provided
    if (updates.items) {
      // Delete existing items
      await supabase
        .from('meal_template_items')
        .delete()
        .eq('template_id', templateId);

      // Insert new items
      const itemsToInsert = updates.items.map(item => ({
        template_id: templateId,
        food_name: item.foodName,
        food_brand: item.foodBrand,
        calories_per_100g: item.caloriesPer100g,
        protein_per_100g: item.proteinPer100g,
        carbs_per_100g: item.carbsPer100g,
        fats_per_100g: item.fatsPer100g,
        quantity: item.quantity,
        unit: item.unit,
        food_item_id: item.foodItemId,
        custom_notes: item.customNotes
      }));

      const { error: itemsError } = await supabase
        .from('meal_template_items')
        .insert(itemsToInsert);

      if (itemsError) {
        console.error('Error updating template items:', itemsError);
        return null;
      }
    }

    // 3. Return updated template
    return await getMealTemplate(templateId);
  } catch (err) {
    console.error('Exception updating meal template:', err);
    return null;
  }
}

/**
 * Delete meal template (cascade deletes items via DB constraint)
 */
export async function deleteMealTemplate(templateId: string): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('meal_templates')
      .delete()
      .eq('id', templateId);

    if (error) {
      console.error('Error deleting template:', error);
      return false;
    }

    return true;
  } catch (err) {
    console.error('Exception deleting template:', err);
    return false;
  }
}

/**
 * Increment usage count when template is logged
 */
export async function incrementTemplateUsage(templateId: string): Promise<void> {
  try {
    const { error } = await supabase
      .rpc('increment', { row_id: templateId });

    if (error) {
      // Fallback: manual increment
      const { data: template } = await supabase
        .from('meal_templates')
        .select('usage_count')
        .eq('id', templateId)
        .single();

      if (template) {
        await supabase
          .from('meal_templates')
          .update({ usage_count: (template.usage_count || 0) + 1 })
          .eq('id', templateId);
      }
    }
  } catch (err) {
    console.error('Error incrementing template usage:', err);
  }
}

// ===== AUTOMATIC SUGGESTIONS =====

/**
 * Detect meal patterns from nutrition logs and suggest templates
 * Simple frequency-based approach (no ML required for v1)
 */
export async function suggestTemplatesFromHistory(
  nutritionLogs: NutritionLog[],
  minOccurrences: number = 5
): Promise<TemplateSuggestion[]> {
  // Group meals by time of day (rough categorization)
  const mealsByTimeOfDay: { [key: string]: NutritionItem[][] } = {
    breakfast: [],
    lunch: [],
    dinner: [],
    snack: []
  };

  // Analyze logs from last 30 days
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

  nutritionLogs.forEach(log => {
    const logDate = new Date(log.date);
    if (logDate < thirtyDaysAgo) return;

    // Simple heuristic: categorize by item count and typical meal times
    // In production, could use timestamps if available
    const itemCount = log.items.length;
    
    if (itemCount >= 2) {
      // Assume multi-item meals are breakfast/lunch/dinner
      // Could enhance with time-of-day analysis
      mealsByTimeOfDay.breakfast.push(log.items);
    } else if (itemCount === 1) {
      mealsByTimeOfDay.snack.push(log.items);
    }
  });

  // Find recurring patterns
  const suggestions: TemplateSuggestion[] = [];

  Object.entries(mealsByTimeOfDay).forEach(([category, meals]) => {
    // Create signature for each meal (sorted food names)
    const mealSignatures = meals.map(items => {
      const signature = items
        .map(item => item.name.toLowerCase().trim())
        .sort()
        .join('|');
      return { signature, items };
    });

    // Count occurrences of each signature
    const signatureCounts = new Map<string, { count: number; items: NutritionItem[]; lastSeen: string }>();

    mealSignatures.forEach(({ signature, items }) => {
      const existing = signatureCounts.get(signature);
      if (existing) {
        existing.count++;
      } else {
        signatureCounts.set(signature, {
          count: 1,
          items,
          lastSeen: new Date().toISOString()
        });
      }
    });

    // Filter by minimum occurrences
    signatureCounts.forEach(({ count, items, lastSeen }) => {
      if (count >= minOccurrences) {
        // Create suggestion
        const templateItems: Omit<MealTemplateItem, 'id' | 'templateId' | 'createdAt'>[] = items.map(item => ({
          foodName: item.name,
          caloriesPer100g: item.calories, // Assuming stored as per 100g
          proteinPer100g: item.protein,
          carbsPer100g: item.carbs,
          fatsPer100g: item.fats,
          quantity: 100, // Default quantity
          unit: 'g'
        }));

        const confidence = Math.min(count / 10, 1); // Cap at 1.0

        suggestions.push({
          template: {
            name: `Suggested ${category.charAt(0).toUpperCase() + category.slice(1)}`,
            category: category as MealCategory,
            isAutoGenerated: true,
            usageCount: 0,
            items: templateItems as MealTemplateItem[]
          },
          confidence,
          occurrences: count,
          lastSeen
        });
      }
    });
  });

  // Sort by confidence/occurrences
  return suggestions.sort((a, b) => b.occurrences - a.occurrences);
}

/**
 * Convert template to nutrition items for logging
 */
export function templateToNutritionItems(template: MealTemplate): Omit<NutritionItem, 'id'>[] {
  return template.items.map(item => {
    const multiplier = item.quantity / 100;
    return {
      name: item.foodBrand ? `${item.foodBrand} - ${item.foodName}` : item.foodName,
      calories: Math.round(item.caloriesPer100g * multiplier),
      protein: Math.round(item.proteinPer100g * multiplier * 10) / 10,
      carbs: Math.round(item.carbsPer100g * multiplier * 10) / 10,
      fats: Math.round(item.fatsPer100g * multiplier * 10) / 10,
      type: 'food' as const
    };
  });
}
